#:schema https://mago.carthage.software/1.40.1/schema.json
# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/1.40.1/en/tools/overview/
version = "1"
php-version = "8.5.0"

[source]
paths = ["src", "test"]
includes = ["vendor"]
excludes = []

[source.glob]
literal-separator = true

[formatter]
preset = "default"
preserve-breaking-member-access-chain = true
preserve-breaking-member-access-chain-first-method-on-same-line = true
preserve-breaking-argument-list = true
preserve-breaking-array-like = true
preserve-breaking-parameter-list = true
preserve-breaking-attribute-list = true
preserve-breaking-conditional-expression = true
preserve-breaking-condition-expression = true
preserve-redundant-logical-binary-expression-parentheses = true

[linter]
integrations = ["laminas", "phpunit"]

[linter.rules]
ambiguous-function-call = { enabled = false }
literal-named-argument = { enabled = false }
halstead = { effort-threshold = 7000 }

# Maintainability
# Exclude test from this rule
too-many-methods = { exclude = ["test/"] }

[analyzer]
plugins = ["psr-container"]
find-unused-definitions = true
find-unused-expressions = true
analyze-dead-code = true
memoize-properties = true
check-throws = true
unchecked-exceptions = ["Error", "LogicException"]
unchecked-exception-classes = []
check-missing-override = true
find-unused-parameters = true
strict-list-index-checks = true
strict-array-index-existence = true
allow-array-truthy-operand = false
no-boolean-literal-comparison = true
check-missing-type-hints = true
register-super-globals = false

class-initializers = [
    "PHPUnit\\Framework\\TestCase::setUp"
]